[project]
name = "durable-python"
version = "0.1.0"
description = "Make python code durable"
authors = [
    {name = "Amol Kelkar",email = "kelkar.amol@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cloudpickle>=2.0.0",
]

[project.optional-dependencies]
disk = [
    "cloudpickle>=2.0.0",
]

[tool.poetry]
packages = [{include = "durable", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
pytest-asyncio = "^0.23.8"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
